version: '3.9'
services:
  node:
    container_name: domain-checker-app
    image: domain-checker-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - domain-checker-network

networks:
  domain-checker-network:
    driver: bridge
